name: Generate Snapshot

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "5 0 * * *"
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
        cache: true
        cache-dependency-path: go.sum

    - name: Install dependencies
      run: go mod tidy

    - name: Generate snapshot images
      run: go run ./main.go
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED_REPOS: ${{ secrets.EXCLUDED_REPOS }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        INCLUDE_FORKED_REPOS: ${{ secrets.INCLUDE_FORKED_REPOS || 'false' }}
        INCLUDE_EXTERNAL_REPOS: ${{ secrets.INCLUDE_EXTERNAL_REPOS || 'false' }}
        INCLUDE_PROFILE_VIEWS: ${{ secrets.INCLUDE_PROFILE_VIEWS || 'false' }}

    - name: Commit to the repo
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'feat: updated snapshot images'
        file_pattern: generated/*
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: ''
